apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# namespace to deploy all Resources to
namespace: cleanup-jobs

# Disable random hash suffix
generatorOptions:
  disableNameSuffixHash: true

# list of Resource Config to be Applied
resources:
  - clusterrolebinding.yaml
  - service-account.yaml
  - taskrun.yaml

# Patch ns for rolebinding sa reference
patchesJson6902:
- target:
    kind: ClusterRoleBinding
    group: rbac.authorization.k8s.io
    version: v1
    name: cleanup-job-sa-rolebinding
  patch: |-
    - op: replace
      path: /subjects/0/namespace
      value: 'cleanup-jobs'

# Create our travis token secret
secretGenerator:
- name: travis-token
  env: travis-token.secret
