kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cleanup-job-sa-rolebinding
subjects:
  - kind: ServiceAccount
    name: cleanup-job-service-account
    namespace: cleanup-jobs
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin